### ISSUE TITLE
Orb failing to find issue keys in branch name or commit message  

### ISSUE THREAD

**Issue by nicduke38degrees** [CircleCI-Public/jira-orb#16]
```yaml
version: 2.1

orbs:
  jira: circleci/jira@2.0.1

jobs:
  build:
    docker:
        <removed>
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: npx tsc --noEmit --skipLibCheck
      - run: yarn test-coverage --runInBand --detectOpenHandles --forceExit
      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
workflows:
  build-workflow:
    jobs:
      - build:
          context: JIRA_WEBHOOK
```

We have set `JIRA_WEBHOOK_URL` as a project environment variable in CircleCI.

When `jira/notify` runs it prints:

```shell
No issue keys found in branch, commit message, or tag
  Branch: PROJECT-3
  Commit: PROJECT-3 my commit message
  Tag: 


Skipping Jira notification
```

Looking at the bash script my only thought was that perhaps the `JIRA_VAL_ISSUE_REGEXP` isn't matching correctly to my issue names? But idk where to look for a value of `JIRA_VAL_ISSUE_REGEXP` so got stuck on debugging that. Any guidance would be appreciated.
