### ISSUE TITLE
[Question] What value should I provide to `environment`?

### ISSUE THREAD

**Issue by ericgrubaughcompass** [CircleCI-Public/jira-orb#17]
I don't understand what the `environment` string should be.

Using this code:
```yaml
      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
          environment: 'sb1'
          environment_type: 'development'
          job_type: deployment
```
The resulting Deployment looks like:

![image](https://github.com/CircleCI-Public/jira-orb/assets/96068756/48899545-5c50-42d0-8d1c-968a71c623d0)

I was expecting the display name of the Environment to be `'sb1'`, but looking at the Orb source, it places my `environment` value in the `id` property of an `environment`. What ID is expected here? Where are these Environments/IDs defined?
