### ISSUE TITLE
Notify Jira step failing with exit code 127

### ISSUE THREAD

**Issue by tmannherz** [CircleCI-Public/jira-orb#21]
We had a CircleCI/Jira integration set up for multiple repos and sometime around 9/13/23 they all started failing silently, similar to what was reported in https://github.com/CircleCI-Public/jira-orb/issues/15.

As I started investigating, I saw that a new version of the Jira Marketplace app and the jira orb had been released.
I updated our orb settings (we were on circleci/jira@1.3.1, now on 2.0.1) and followed the directions in https://circleci.com/docs/jira-plugin/ to re-install and configure the Jira Marketplace app.

For 3/4 repos, that was successful. In the fourth, which seemingly has the same config, the `Notity Jira` step is failing with exit code 127.

With debugging enabled, the output looks like this:
![image](https://github.com/CircleCI-Public/jira-orb/assets/533798/13486f18-f6de-4cfe-ad1d-d3cd95d42de8)

```
environment: line 118: jq: command not found
environment: line 118: jq: command not found

Exited with code exit status 127
```

Line 118 in the "Show more" output is a bash comment, so I wasn't able to further debug this failure.

Our workflow config looks like this:
```yaml
  Dev Build:
    when:
      and:
        - not:
            equal: [ production, << pipeline.git.branch >> ]
        - not:
            equal: [ development, << pipeline.git.branch >> ]
    jobs:
      - test_build:
          context:
            - slack
            - jira
          post-steps:
            - jira/notify:
                debug: true
                environment_type: testing
                job_type: build
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
```

Any insight into what's failing? I'm going to have to remove the Jira orb from this workflow because its failure causes the entire workflow to be reported as failing, blocking our deployments.
