### ISSUE TITLE
v2 jira/notify keeps adding new builds

### ISSUE THREAD

**Issue by kevin--** [CircleCI-Public/jira-orb#33]
Every time a dev pushes to their branch, it seems the tooling keeps adding a new build.

We have it set up as a command in our workflow.yml
```
  jira-notify:
    description: Notify JIRA
    steps:
      - jira/notify:
          ignore_errors: false
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
```
since we have many different setups depending on what artifacts have been cached, which architectures we need to build, etc (we run a Setup step).

At any rate, we run the `jira-notify` command as a `post-steps` on the final job in the pipeline.

As shown in the screenshot below, each job has a new `pipeline_id` and `pipeline_number`. The V1 Jira Orb would only keep the latest build here for a given ticket/branch, and we would like to restore that functionality. QA shouldn't have to read a list to figure out which build to test.

![image](https://github.com/CircleCI-Public/jira-orb/assets/3334774/b4dab1c0-20c0-46b7-a117-472a9ac8be6a)

Can we override `pipeline_id` to `0` or something to make them all merge into 1 item in the list?
