### ISSUE TITLE
jira/notify stopped working within the last 24 hours

### ISSUE THREAD

**Issue by Kazark** [CircleCI-Public/jira-orb#52]
Suddenly, without changing our configuration, we are getting 424's on our builds. Our configuration:

```yaml
  notification:
    steps:
      # Call master production
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - jira/notify:
                debug: true
                environment: production
                environment_type: production
                job_type: deployment
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
      # Otherwise call it testing and assume it's in the dev environment
      - when:
          condition:
            not:
              equal: [master, << pipeline.git.branch >>]
          steps:
            - jira/notify:
                debug: true
                environment: dev
                environment_type: testing
                job_type: deployment
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
      - run: echo 0
```

We were on version 2.0.1 of the Orb, so I upgraded to 2.2.0. This allowed me to turn error ignoring on to stop the bleeding, but it doesn't solve the problem. Here is a sanitized version of the debug output:

```
Debugging Enabled

  #### DEBUG ####
  OIDC Token: *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Webhook URL: ***************************************************************************************************?verbosity=log
Environment: dev
  ###############


  #### DEBUG ####
  GETTING TAG KEYS
  ###############

Issue keys found:
JIRA-6006
Notification type: deployment

  #### DEBUG ####
  PAYLOAD: {
  "deployments": [
    {
      "deploymentSequenceNumber": "19924",
      "updateSequenceNumber": "1748524991",
      "associations": [
        {
          "associationType": "issueIdOrKeys",
          "values": [
            "JIRA-6006"
          ]
        },
        {
          "associationType": "serviceIdOrKeys",
          "values": [
            ""
          ]
        }
      ],
      "displayName": "Deployment #19924 of our-project",
      "url": "https://circleci.com/gh/OurCompany/our-project/131564",
      "description": "Deployment successful",
      "lastUpdated": "2025-05-29T18:23:11.000Z",
      "label": "Release 2025-05-29T18:23:11.000Z::19294",
      "state": "successful",
      "pipeline": {
        "id": "eac5d4a2-4389-f953-2495-aaf332484e46",
        "displayName": "Deployment: our-project::19924",
        "url": "https://app.circleci.com/pipelines/gh/OurCompany/our-project/19924"
      },
      "environment": {
        "id": "dev",
        "displayName": "DISPLAY_NAME",
        "type": "testing"
      },
      "schemaVersion": "1.0"
    }
  ],
  "providerMetadata": {
    "agent": "circleci-orb"
  }
}
  ###############

Posting payload to CircleCI for Jira Forge app

  #### DEBUG ####
  HTTP Status: 424
HTTP Body: {"timestamp":"2025-05-29T18:23:12.113+00:00","path":"<PATH>","status":424,"error":"Failed Dependency","requestId":"1fb3f172-4118815"}
  ###############


Error posting payload to CircleCI for Jira Forge app
  HTTP Status: 424
  Errors:
parse error: Invalid numeric literal at line 1, column 7

Exited with code exit status 4
```

Let me know what other information I can provide to help you track down this issue.
